version: '3'

services:
  django:
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
#    command: sh -c "rm -rf /var/lib/postgresql/data/* && docker-entrypoint.sh postgres"
    ports:
      - '5432:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -d $${POSTGRES_USER} -U $${POSTGRES_DB}' ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  celery:
    build: .
    tty: true
    env_file: .env
    command: celery -A config worker -l info
    depends_on:
      - postgres
      - redis
      - celery_beat

  celery_beat:
    build: .
    tty: true
    env_file: .env
    command: celery -A config beat -l info -S django
    depends_on:
      - postgres
      - redis

volumes:
  pg_data: